### ISSUE TITLE
Rename fields in shared interfaces

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#10]
## 📚 Context

@diegonehab pointed out that keccakInHashesSiblings in OutputValidityProof is confusing because it doesn't represent what the variable actually is.

There is also some confusion regarding input indices being local or global.

These variables are present in the OutputValidityProof structure across the Cartesi Rollups infrastructure, so this PR involves multiple repositories.

## ✔️ Solution

We should rename keccakInHashesSiblings to outputHashInOutputHashesSiblings.
We should rename the <Output/Input>Index to <Output/Input>IndexWithinEpoch or epoch<Output/Input>Index.

## 📈 Subtasks

- [ ] Rename it in grpc-interfaces repo
- [ ] Rename it in server-manager (machine-emulator repo)
- [ ] Rename it in host-server-manager (host-server-manager repo)
- [ ] Rename it in GraphQL API (offchain/graphql-server)
- [ ] Rename it in PostgreSQL (offchain/data)
- [ ] Rename it in Broker (offchain/rollups-events)
- [ ] Rename it in onchain code

**Comment by gligneul** [comment]
I merged the PR on https://github.com/cartesi/grpc-interfaces/pull/13. I will apply this modification to the rollups repository (offchain and onchain code). 
I also plan to migrate the host-server-manager to this repository, so all our changes will be in one place. This will be done in the following issue: https://github.com/cartesi/grpc-interfaces/pull/13

**Comment by gligneul** [comment]
The offchain changes were merged in #122. The onchain changes will be tracked in #123.
