### ISSUE TITLE
Decide Metrics Tecnology

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#11]
## 📚 Context

We need to improve the observability of the Cartesi Node by exposing domain-driven metrics.

## ✔️ Solution

First, we have to decide what technology we are going to use. The two main possibilities are Prometheus and OpenTelemetry. [This article](https://www.timescale.com/blog/prometheus-vs-opentelemetry-metrics-a-complete-guide/) might help. It would be nice to prepare a presentation and then decide on it together. 

Then, we have to decide which metrics we want to expose. @endersonmaia, @tuler, and I already agreed on a few metrics for the dispatcher and the advance runner. Bellow, there is a list of desired metrics for the Rollups MVP. All of them are counters.

### Dispatcher

- dispatcher_claims_sent_total
- dispatcher_advance_inputs_sent_total
- dispatcher_finish_epochs_sent_total

### Advance Runner

- proxy_advance_inputs_processed_total
- proxy_epochs_finished_total
- proxy_claims_sent_total

Finally, we have to create the appropriate issues and implement these metrics.

## 📈 Subtasks

- [x] Decide which metrics technology we are going to use.
- [x] Define what metrics we are going to expose in each service.
- [x] Create one issue for each service that should have metrics.
- [x] Create an epic issue that points to all these issues.

## 🎯 Definition of Done

- [x] Issues specifying the work that needs to be done.

**Comment by renan061** [comment]
We decided to use Prometheus for metrics and, in the future, explore OpenTelemetry for tracing.
