### ISSUE TITLE
Document node config options

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#111]
## 📚 Context

To know the config options of the node services, the user needs to run the service with the help flag. This is cumbersome because the user can't easily see the modifications on the config.

## ✔️ Solution

Document and commit the config options for the node. We should ensure this doesn't get outdated, so it should be done with a script. We should also check on the CI to see whether it is updated.

This approach avoids committing in the CI.

## 📈 Subtasks

- [ ] Create a script to document the node config options.
- [ ] Commit the node config options.
- [ ] Run the script on the CI to check whether it is current.

**Comment by gligneul** [comment]
@tuler @endersonmaia what do you think?

**Comment by tuler** [comment]
I don't really understand the problem.
I think whenever there is a breaking change that has to be part of the changelog.
And that can't be automated, or is too complicated to automate, or not worth it, IMO.

**Comment by tuler** [comment]
> help you detect the changes in the node config.

Do we need that @endersonmaia ?

**Comment by endersonmaia** [comment]
we need to know breaking changes in the cli arguments

if that's going to be detected via CI or via changelogs is the debate here if I got it right 

I like the automated approach

**Comment by tuler** [comment]
I think that when upgrading from, let's say 0.9.0 to 0.10.0, you have to read the changelog, and see what are the breaking changes.

It's not just a matter of CLI breaking changes, all breaking changes, CLI changes included.
I don't see a point of automating just the CLI part.
And I don't think there is a way to automate all.

Still smells like over-engineering to me.

**Comment by gligneul** [comment]
Ok, I agree that this can be handled in the changelog.
