### ISSUE TITLE
Rename fields in output validity proof

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#123]
## 📚 Context

Last month, we agreed on the new names for some fields in the output validity proof structure. We need to apply these changes to the rollups repo as well. I renamed the fields in the offchain directory in #122. In this issue, we should rename them in the onchain directory.

The changes are:

- input_index :arrow_right: input_index_within_epoch
- output_index :arrow_right: output_index_within_input
- keccak_in_hashes_siblings :arrow_right: output_hash_in_output_hashes_siblings

Here is the PR where we agreed on the changes: https://github.com/cartesi/grpc-interfaces/pull/13

## ✔️ Solution

Rename the fields in the onchain part of the project.

## 📈 Subtasks

(Feel free to change the subtasks.)

- [ ] Rename fields in contracts
- [ ] Rename fields in foundry tests
- [ ] Rename fields in documentation

**Comment by guidanoli** [comment]
Just pointing out that these names would be written in `camelCase` in Solidity. :-)
