### ISSUE TITLE
Create a common base contract for portals and relays

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups#131]
## 📚 Context

As previously discussed in #33, portals and relays have isomorphic interfaces.
We decided to name this common interface "Input Relay".
However, currently portals and relays have different base interfaces.

## ✔️ Solution

We should remove the "Portal" and "Relay" interfaces, and add an "Input Relay" interface. The same goes for the base implementations.

## 📈 Subtasks

- [ ] Add `IInputRelay.sol` and `InputRelay.sol`
- [ ] Make portals and relays use `IInputRelay.sol` and `InputRelay.sol`
- [ ] Remove `IPortal.sol` and `Portal.sol`
- [ ] Remove `IRelay.sol` and `Relay.sol`
