### ISSUE TITLE
Generate a single proof library for all outputs

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups#144]
## 📚 Context

Currently, the `genProofLibraries.ts` script is generating one library for each output.
As a result, in the `CartesiDApp.t.sol` file, there are numerous imports, one for each output.
When the developer wants to add a new output test, they must add a new import to this list.
Additionally, they must also increment the `NINPUTS` constant in the `update-proofs.sh` script.

## ✔️ Solution

To mitigate this issue, we can generate a single library containing the proofs for all vouchers and notices in separate functions `getVoucher<N>Proof()` and `getNotice<N>Proof()`.

## 📈 Subtasks

- [ ] Change the `genProofLibraries.ts` file to generate a single library
- [ ] Change the `CartesiDApp.t.sol` file to import and use this library
- [ ] Verify that everything is working as expected
