### ISSUE TITLE
Extinguish `ConsensusCreated` emitted by `Authority`

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups#155]
## 📚 Context

As soon as one deploys an `Authority` contract, it emits an event called [`ConsensusCreated`](https://github.com/cartesi/rollups/blob/main/onchain/rollups/contracts/consensus/authority/Authority.sol#L33-L37) which contains the following parameters:

* `owner`: the address that has ownership over the authority contract
* `inputBox`: the address of the [`IInputBox`](https://github.com/cartesi/rollups/blob/main/onchain/rollups/contracts/inputs/IInputBox.sol) that the authority will listen to `InputAdded` events

We argue that the `ConsensusCreated` event can be extinguished by showing that each parameter can already be retrieved in another way, or doesn't capture well how the Authority works in practice.

* `owner`: this information is already emitted through [`OwnershipTransferred`](https://docs.openzeppelin.com/contracts/2.x/api/ownership#Ownable-OwnershipTransferred-address-address-) events (see OpenZeppelin's [`Ownable`](https://docs.openzeppelin.com/contracts/2.x/api/ownership#Ownable) contract)
* `inputBox`: this assumes that the authority will listen to exactly one input box forever. This does not take multiple input boxes into consideration. This will be the case whenever (and if) a new version of the input box contract is released and deployed. Furthermore, it makes more sense for this parameter to be application-specific, and not consensus-specific. For example, an input box could allow bigger inputs because the off-chain machine running the DApp back-end allows.

## ✔️ Solution

We may remove the `ConsensusCreated` event from the `Authority` contract.
We need to make sure this is not a breaking change for the off-chain.

As a result, the `IInputBox` argument passed to the constructor of the `Authority` contract can be removed.
This change will have cascading effects in #64, #99, and #85.

## 📈 Subtasks

- [ ] Remove the event
- [ ] Update the on-chain tests
- [ ] Verify that the off-chain runs fine

**Comment by gligneul** [comment]
I couldn't find any mention of ConsensusCreated in the node code. So I believe we don't use it.

**Comment by guidanoli** [comment]
> I couldn't find any mention of ConsensusCreated in the node code. So I believe we don't use it.

Great news, then! :-)

**Comment by DaniOrtegaB** [comment]
I've one concern about removing it. How can dApp will known which Consensus exists? I thought that with this event we can manage to know when a Consensus is created. What are the options for a dApp to subscribe or change consensus? it should've some way to know the existing ones.

**Comment by tuler** [comment]
> How can dApp will known which Consensus exists?

Through a factory.

**Comment by DaniOrtegaB** [comment]
> > How can dApp will known which Consensus exists?
> 
> Through a factory.

Seems to be a good approach. We have to define this new feature and the set of contracts before removing all the information related with the creation of a new consenus, right? Or just have something decided to cover this.
