### ISSUE TITLE
CI tests for the AWS KMS signer

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups#16]
## 📚 Context

The tests for the AWS KMS signer must be executed manually due to authentication restrictions.
They are currently being ignored in the CI.

## ✔️ Solution

- We can try to mock what we need locally.
- We can add the necessary authentication to the CI.

We don't know which solution is more viable.
We need to explore it further.

## 📈 Subtasks

- [ ] Study the solutions and decide which one is more viable.
- [ ] Implement the solution.

## 🎯 Definition of Done

- [ ] Tests for the AWS KMS signer running in the CI.

**Comment by renan061** [comment]
We can probably use [LocalStack](https://docs.localstack.cloud/references/coverage/coverage_kms) to test things locally, as pointed out by @endersonmaia.

**Comment by tuler** [comment]
Is the support for KMS included in 0.9.0?
How do we configure the node to use KMS instead of a MNEMONIC?

**Comment by gligneul** [comment]
@tuler, the KMS support was not included in version 0.9.0. It was merged into the main branch.

**Comment by gligneul** [comment]
We provide these parameters to configure the AWS KMS signer
```
      --auth-aws-kms-key-id <AUTH_AWS_KMS_KEY_ID>
          AWS KMS signer key-id [env: AUTH_AWS_KMS_KEY_ID=]
      --auth-aws-kms-region <AUTH_AWS_KMS_REGION>
          AWS KMS signer region [env: AUTH_AWS_KMS_REGION=]
```

**Comment by tuler** [comment]
Ok. @endersonmaia I see the options in `docker run ghcr.io/cartesi/rollups-dispatcher:main --help`

```
--auth-aws-kms-key-id <AUTH_AWS_KMS_KEY_ID>          AWS KMS signer key-id [env: AUTH_AWS_KMS_KEY_ID=]
--auth-aws-kms-region <AUTH_AWS_KMS_REGION>          AWS KMS signer region [env: AUTH_AWS_KMS_REGION=]
```
