### ISSUE TITLE
Import state-fold to offchain

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups#182]
## 📚 Context

State-fold is an auxiliary library that is currently being used only by the dispatcher and it's in another repository in Github.

## ✔️ Solution

Bring the state-fold as another crate inside offchain and have the rest of the offchain code use the new crate.

## 📈 Subtasks

- [] Create the state-fold crate
- [] Import the state-fold code from the repository with the same name
- [] Update necessary code inside the offchain to point to the internal state-fold
