### ISSUE TITLE
Refactor dispatcher to remove claims

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups#188]
## 📚 Context

With the `authority-claimer` responsible for the claims, this section of the dispatcher code will be deprecated.

## ✔️ Solution

Remove the redundant code from the dispatcher.

## 📈 Subtasks

- [ ] Remove main loop calls
- [ ] Remove blockchain driver
- [ ] Remove obsolete auxiliary methods and tests
