### ISSUE TITLE
Migrate node to cartesi/rollups-node

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#193]
## 📚 Context

As the node unit, we want more control over the git repository.

## ✔️ Solution

Migrate the node codebase to https://github.com/cartesi/rollups-node

## 📈 Subtasks

- [x] Create the new repository
- [ ] Move the code to the new repository
- [ ] Create milestones in the new repository
- [ ] Migrate issues to the new repository
- [ ] Remove onchain code from the new repository
- [ ] Remove offchain code from the old repository
