### ISSUE TITLE
Migrate host-server-manager to rollups repository

### ISSUE THREAD

**Issue by torives** [cartesi/rollups#23]
## 📚 Context

Most Cartesi Node services live together in the rollups repository enjoying the benefits of a monorepo: code reuse, simplified dependency management, etc. Unfortunately, the host-server-manager is an exception. It would be beneficial to move it to the monorepo so it could be better integrated with the other Rust services already in there.

## ✔️ Solution

Archive the host-server-manager repository and move its code to the rollups repo.

## 📈 Subtasks

- [ ] Move host-server-manager code to the rollups repository
- [ ] Adapt the project's configuration and dependencies to the new Cargo workspace
- [ ] Integrate its build, test, and release processes to the existing ones
- [ ] Archive the host-server-manager repository
