### ISSUE TITLE
Standardize node binaries names

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#26]
## 📚 Context

Some binaries use underscore and others use hyphens as separators. Also, some binaries have the rollups prefix and others don't. 

## ✔️ Solution

We should decide on a standard and rename the offending binaries.

## 📈 Subtasks

- [ ] Decide the standard
- [ ] Rename binaries in Cargo.toml and in Dockerifle
- [ ] Make sure everything is working as we don't have CI tests for the generated docker images.

## 🎯 Definition of Done

- [ ] Binary names updated.
