### ISSUE TITLE
Unify Node Configuration

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#27]
## 📚 Context

Today the node configuration is done via CLI arguments, ENV variables, and files. Moreover, each service has its own way of getting the config parameters, some use Clap and others use StructOpt. And some of these parameters have the same semantics but different names in different services.

## ✔️ Solution

My proposal is to create a single crate that contains all the configurations. This will be a lightweight crate that all services will import.

I would also like to remove the support for CLI arguments and stop using clap and struct-opt. Since ENV variables are much simpler to parse, we don't need an external crate to do this job.

Some arguments, like DApp deployment, should be read from files because of the rollups-examples docker-compose. However, we should consider supporting these arguments via ENV as well.

The environment variables for each service should have a prefix with the name of the service. For instance, the variables CHAIN_ID for the advance-runner should be CARTESI_NODE_ADVANCE_RUNNER_CHAIN_ID.

Finally, we should generate the documentation of all options in a single place. Once we stop to use clap, the services will not have the help option anymore.

## 📈 Subtasks

- [ ] Create a crate that holds all config variables
- [ ] Move all config to this single crate
- [ ] Add prefix support to the env vars
- [ ] Rename config variables with the same meaning
- [ ] Automatically generate the config documentation

## 🎯 Definition of Done

- [ ] PR merged

**Comment by tuler** [comment]
Why don’t you like clap or struct_opts?
Don’t they also provide automatic env variables handling?

**Comment by gligneul** [comment]
I believe the client code would be simpler if we didn't use these libraries. For instance, currently, we have to define the config twice and convert between the CLI config and the "final" config. These libraries are very useful for parsing command line arguments, but if we are only interested in environment variables I don't think they are necessary. 

More importantly, clap (and struct-opt) doesn't allow setting prefixes when flattening a sub-config. There are more details in https://github.com/clap-rs/clap/issues/3117. When talking with @endersonmaia, I felt that adding prefixes to the environment variables would greatly simplify running the node in a single container.

**Comment by gligneul** [comment]
There is another issue in clap with a more limited scope that would solve our problem: https://github.com/clap-rs/clap/issues/3221
However, it is not implemented yet.

**Comment by gligneul** [comment]
@endersonmaia and I talked and we came to a few conclusions.

1. We should keep the CLI options because they are often useful when debugging. Then, we should migrate all config that still uses struct-opt to clap.
2. The health check is the only config that needs a prefix because we want to configure different ports for each service. We probably can solve that with a macro. The other configs should not have prefixes or else we would need to redefine multiple times.
3. We need to make a few improvements overall. We should use sensible defaults for everything we can. We need to improve the documentation of some variables. For instance, why --tx-default-confirmations in the dispatcher is different from --sc-default-confirmations?  We should either document well the variables' prefixes or remove them. In the dispatcher we have, HC, RD, SC, and TX.
