### ISSUE TITLE
Define scopes for conventional commits

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#31]
## 📚 Context

We started using conventional commits but we are using ad-hoc scopes.

## ✔️ Solution

We should define the possible scopes, document them, and add a verification to the CI. I would highly recommend that we follow the angular contributing guideline. https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines

## 📈 Subtasks

- [x] Define the possible scopes for the rollups project.
- [x] Document the scopes in the contributing.md file. (See the angular one).
- [x] Add the scopes to the CI verification.

## 🎯 Definition of Done

- [x] Scopes documented
- [x] Automatic verification on CI

**Comment by GMKrieger** [comment]
I've spoken with @guidanoli about this, and we agreed on the following design.

We're going to use the same format as Angular for commit messages

```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

Where type, scope and subject will be required, and body and footer will be optional.

The types will be as follows:

```
build: Changes that affect the build system or external dependencies (example: npm)
feat: A new feature
fix: A bug fix
test: Adding missing tests or correcting existing tests
perf: A code change that improves performance, but otherwise keeps the same functionality
refactor: A code change that neither fixes a bug nor adds a feature
docs: A documentation only change
style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
```

The types also follow this hierarchy, meaning if there are changes in a single commit that would fit multiple types, choose the one first on the list.

As for the scopes, we defined the following list:

```
advance-runner
offchain-contracts
data
dispatcher
graphql-server
grpc-interfaces
http-health-check
indexer
inspect-server
redacted
rollups-events
state-server
test-fixtures
types
onchain-contracts
deploy
arbitration
cli
```

That's a scope for every crate on the offchain module, and a scope for each 4 main working points on the onchain module, as specified with Guilherme

Open to suggestions @gligneul @torives @renan061

**Comment by gligneul** [comment]
I think the list is fine. We have to make sure to document this decision in the CONTRIBUTING.md and add a check in the CI to enforce it.

**Comment by GMKrieger** [comment]
Ok, so I created a v1 of the CONTRIBUTING.md document. All feedback is much appreciated!

[CONTRIBUTING.md](https://github.com/cartesi/rollups/files/11436589/CONTRIBUTING.md)

**Comment by gligneul** [comment]
@GMKrieger could you create a draft PR so we can comment there?

**Comment by marcelstanley** [comment]
I like [@torives's suggestions](https://github.com/cartesi/rollups/issues/31#issuecomment-1536391920) but I'd vote for keeping the 50-char limit to the subject line... And he knows it. 😄
