### ISSUE TITLE
Name the superset containing portals and relays

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups#33]
## 📚 Context

In the on-chain architecture, there are two categories of input-adding contracts called portals and relays. Both classes are designed to inform the machine running in the execution layer of events that take place in the base layer. In particular, the events informed by portals are asset transfers.

In order to avoid code duplication and inconsistencies, we define interfaces and base contracts for both portals (`IPortal` and `Portal`) and relays (`IRelay` and `Relay`). Soon we noticed, however, that portals and relays had isomorphic interfaces and base contracts (`IPortal` $\sim$ `IRelay`, and `Portal` $\sim$ `Relay`), which leads to exactly what we were trying to avoid—code duplication.

## ✔️ Solution

Have a single interface and base contract for both portals and relays. We need, therefore, to find a good name for the superset that contains portals and relays. This process should proceed democratically.

## 📈 Subtasks

- [x] Raise options for the name
- [x] Create poll with all the raised options on the [`#rollups`](https://discordapp.com/channels/600597137524391947/1104007675370553505) Discord channel

## 🎯 Definition of Done

- [x] Poll created
- [x] Poll closed (and winner elected)

**Comment by guidanoli** [comment]
Some options that have been raised already include:

* Relay: you can think of portals are relays that do something else other than informing the off-chain machine of something—they perform asset transfers too.
* Messenger: a contract that sends a message to the off-chain machine
* Input adder: a contract that adds an input to the DApp's input box

**Comment by felipeargento** [comment]
Nice!
But I think we have to make sure that the former 'portals' are very explicit about dealing with assets...something like EtherDepositRelayer, instead of EtherRelayer.

Some other options for the poll:
- Bridge
- Informer
- Snitch
- Announcer

(I love snitch, but I might be biased toward silliness haha)

**Comment by guidanoli** [comment]
> Bridge

I would avoid the word "bridge", as it has gained a bad reputation for being unsafe and unstable.

**Comment by felipeargento** [comment]
> > Bridge
> 
> I would avoid the word "bridge", as it has gained a bad reputation for being unsafe and unstable.

Bridges have definitely been the target of many attacks! However, I think that there are two things happening that make "bridge" a valid contender for the poll:
1) Some people frame rollups as a validating bridge. Or, as Bartek from L2 put it, on his devcon talk: [Rollups Are the Most Secure Bridges](https://archive.devcon.org/archive/watch/6/rollups-are-the-most-secure-bridges/?tab=YouTube). Or this article from Patrick, called [deconstructing rollups](https://stonecoldpat.substack.com/p/deconstructing-rollups).
2) [Arbitrum](https://bridge.arbitrum.io/), [Optimism](https://app.optimism.io/bridge/deposit) and other rollups in the industry also use the name bridge for their mechanism of teleporting assets from L1 to L2.

I wouldnt necessarily call it bridge, because we're using it for other stuff like addresses, chain id etc. But I think it should at least appear in the poll options :)

**Comment by tuler** [comment]
> 2. [Arbitrum](https://bridge.arbitrum.io/), [Optimism](https://app.optimism.io/bridge/deposit) and other rollups in the industry also use the name bridge for their mechanism of teleporting assets from L1 to L2.

I think they use bridge, but they also use "messenger" as the underlying mechanism of bridges.

**Comment by guidanoli** [comment]
> But I think we have to make sure that the former 'portals' are very explicit about dealing with assets...something like EtherDepositRelayer, instead of EtherRelayer.

Yes, of course. We are only interested in naming the base contract! Contracts that inherits from this base contract can be called whatever! So, portals will still be portals, relays will still be relays. :-)

**Comment by DaniOrtegaB** [comment]
Cool, we can wait until Monday 15th for more ideas and create a poll! I just wanted to highlight a couple ideas for some of the most commonly used names.
- Messenger: It's true that other projects such as Optimism or Arbitrum use this term, but the argument they use in functions is a `bytes message`, so I'd say it doesn't entirely fit the scope of token relays.
- Bridge: Maybe it's just a matter of prejudice, but as I read bridge, I think of locking assets in one layer and unlocking in another chain.

**Comment by guidanoli** [comment]
What I don't really like about the term "messenger" is that, by itself, it doesn't define the origin or the destination of the message. In one hand, Arbitrum clears this ambiguity by using the terms ["L1-to-L2 message"](https://developer.arbitrum.io/arbos/l1-to-l2-messaging) and ["L2-to-L1 message"](https://developer.arbitrum.io/arbos/l2-to-l1-messaging). We, on the other hand, are moving away from the L-nomenclature and adopting the terms "base layer" and "execution layer". 

However, instead of using the term "base layer to execution layer message", we could just use the term "input" which is much more succinct. That is why I find the term "input adder", although not as sexy as "portal" or "bridge", quite accurate.

**Comment by miltonjonat** [comment]
Just to be sure, we are considering "Relay" as an option for the basic interface, having "Portal" as a specialization of it, right?

Couple of observations:
- I don't see anything specific to `IRelay` that does not make sense for `IPortal`. If there is, then what is it? If there isn't, then having `IPortal` extend `IRelay` seems to be the best way to go IMHO (or even have all Portals extend `IRelay` if there is nothing to add to `IPortal`).
- Following @guidanoli considerations, we may also consider naming the base interface "InputRelay" to be more specific, if that's an issue (I personally don't see it as an issue).

**Comment by guidanoli** [comment]
@miltonjonat 

> Just to be sure, we are considering "Relay" as an option for the basic interface, having "Portal" as a specialization of it, right?

Yes, one of the options is to adopt the name "relay" as the base, and have the word "portal" simply mean a relay that deals with assets.

> I don't see anything specific to IRelay that does not make sense for IPortal.

That is precisely the reason why we are thinking of merging both into a single basic interface.

**Comment by guidanoli** [comment]
### Poll results :bar_chart: 

The poll was closed on May 23rd. These are the top voted options:

```
1. Input Relay ###### (5)
1. Relay       ###### (5)
2. Bridge      ##     (2)
```

**It is a tie!** To break this tie, the on-chain team in the Rollups Reference Unit (@DaniOrtegaB, @pedroargento, @ZzzzHui and me) has decided to go for the "Input Relay" name under the following reasoning.

The name "relay" itself is too ambiguous. What are we relaying? Are inputs the only thing we can relay? The answer is, we don't know yet. So, in case we use the name "relay" for something else in the future, we are at least specifying what are we relaying: inputs.

Furthermore, it is okay to call the base contract "input relay" and the implementation "DApp address relay" for the same reason it is okay to call an "ERC-20 token holder" an "asset holder" (because ERC-20 tokens are assets, and we are inputting the DApp address in the off-chain machine).

**Comment by guidanoli** [comment]
The winner was "Input Relay".
