### ISSUE TITLE
Node should get credentials from secrets API

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#36]
## 📚 Context

Currently, the node gets its secrets from files, which is not entirely insecure but could be improved.

## ✔️ Solution

Our services should be able to request its credentials/secrets via some API.

In our AWS configuration, we're using AWS SecretsManager to store secrets to the database but not leveraging the rotation.

We could also use a provider, like Hashicorp's Vault, which can handle secrets and credentials, and permissions for database engines like PostgreSQL, Redis, etc.

With tolls like these, we don't configure the database credentials. Still, instead, we ask an API for credentials to be created, and it creates the database and credentials and informs this, and also manages the expiring and rotation of the credentials.

## 📈 Subtasks

- [ ] Define which secrets technology we are going to use.
- [ ] Implement optional support to get the secrets from this technology.
- [ ] Automatic tests in a local environment.
- [ ] Documentation.

## 🎯 Definition of Done

- [ ] PR merged.
