### ISSUE TITLE
Add infrastructure to run the node

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#38]
## 📚 Context

Currently, we rely on the rollups-examples repository to run the node. This is an issue because we need to use another project to know whether the node is working correctly.

## ✔️ Solution

The proposed solution is to add a minimal working example to this repository. This example could use docker-compose to orchestrate the node, just like rollups examples. For the DApp itself, we could use the echo-DApp `ioctloop` already available inside the rootfs from the Cartesi Machine.

The objective of this example will be for developers to test their code, create automated end-to-end tests for the node (in the following issue), and document the necessary orchestration for the node.

## 📈 Subtasks

- [ ] Build cartesi machine snapshot using ioctloop. (See `offchain/test-fixtures/docker/machine_snapshot.Dockerfile`.)
- [ ] Add infrastructure to run the node.
- [ ] Add documentation explaining how to run the node.
- [ ] Add documentation on interacting with the node (send inputs, get outputs, finish epoch, etc.).

## 🎯 Definition of Done

- [ ] PR merged
