### ISSUE TITLE
Implement basic end-to-end test

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#39]
## 📚 Context

We do not have tests that run the whole node and connect to the blockchain contracts, and it is hard to know whether all components are working together as they should or not. In particular, we need to know whether the node (off-chain) is compatible with the smart contracts (on-chain).

## ✔️ Solution

Depends on https://github.com/cartesi/rollups/issues/38.

Once we have the infrastructure necessary to run the node in the rollups repository, we should work on an automatic test that validates that the node is working.

The first test case should send vouchers and notices and assert that they appear in the GraphQL API.

Once we have the necessary setup and the primary test case, we should create other issues to cover more test cases. For instance, finishing epochs, validating notices, executing vouchers, inspecting the state, etc.

## 📈 Subtasks

- [ ] Setup test infrastructure.
- [ ] Implement primary test case.
- [ ] Run the test in the CI.
- [ ] Document how to run the test.
- [ ] Write down the following issues.

## 🎯 Definition of Done

- [ ] PR merged.
- [ ] Following issues created.
