### ISSUE TITLE
Write Node documentation

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#40]
## 📚 Context

It is hard to understand how the crates in the offchain directory work together to form the Node.

## ✔️ Solution

Write a readme file for the offchain part of the project. This file should contain the architectural diagram for the Node and explain what each service of the Node does. 

Here is the current service diagram for the Node. This image also contains data-flow diagrams for the common operations in the Node.

![Screenshot from 2023-05-17 17-05-33](https://github.com/cartesi/rollups/assets/8294320/473169b5-31e4-4ee0-8d45-6e8672ba6336) 

The diagram should be committed to the repository. Ideally, it should be written as code using some tool like [Mermaid](https://mermaid.js.org/).

## 📈 Subtasks

- [x] Create simple diagram for Advance runner case
- [x] Create simple diagram for host mode
- [x] Describe existing data flows
- [x] Describe components
- [ ] Add missing READMEs for consistency sake
