### ISSUE TITLE
Add `AuthorityWithHistory` factory

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups#71]
## 📚 Context

We envision to have factories for `Authority` and `History` separately, to leverage the optimal modularity of on-chain components. However, in order for a validator to deploy an Authority contract and a History contract and link them together, they would need to submit three separate transactions. This can be very pricey, depending on the network in which the contracts are deployed.

## ✔️ Solution

Create a smart contract that allows one to perform all three operations mentioned above in a single transaction. We will call this contract `AuthorityWithHistoryFactory`. This contract should also provide entry points for the deterministic deployment of the individual contracts.

## ⛓ Requires

- [ ] #59
- [ ] #70

## 📈 Subtasks

- [ ] Define the interface
- [ ] Implement the interface
- [ ] Test the contract
- [ ] Create deployment script

**Comment by guidanoli** [comment]
FYI @tuler
