### ISSUE TITLE
Specify external dependencies in the workspace Cargo.toml

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#9]
## 📚 Context

Currently, each crate specifies its dependencies in its own Cargo.toml file. This is precarious because we use different versions of the same external dependency in each crate. Another negative side effect is using different crates for performing the same task. Solving this debt will also help us update the external dependencies more easily since they will all be in the same file.

## ✔️ Solution

Since Rust 1.64 it is possible to specify external dependencies in the workspace Cargo.toml and inherent them in the child Cargo.toml. More details here: https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

## 📈 Subtasks

- [x] Move all dependencies declarations to the workspace's Cargo.toml.
- [x] Make sure all dependencies are in the same version.
- [x] Update the dependencies to the latest major version or create other issues to do that if it requires too much effort.
- [x] Create issues to merge redundant dependencies. For instance, structopt vs clap, axum vs actix-web, anyhow vs snafu, etc.

**Comment by renan061** [comment]
Anyhow in `test-fixtures`.
